# Site Settings
title: The Nature Of Light
email: TheNatureOfLight@gmail.com
description: >
  A Guide to Demystifing the Mathmatics of Spectral Rendering.
baseurl: "/startjekyll"
url: "http://TheNatureOfLight.github.io"
github_username:  TheNatureOfLight
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM